name: znn_stresstest_analysis
description: A very simple zenon stresstest analyser
version: 1.0.0

environment:
  sdk: '>=2.14.4 <3.0.0'


dependencies:
  znn_sdk_dart:
    path: '../znn_sdk_dart'


dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
